[build]
  command = "npm run build"
  publish = "dist"

# Handle client-side routing and 404s
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/404"
  to = "/404/index.html"
  status = 404

# API proxy for Guerrilla Mail
[[redirects]]
  from = "/api/guerrillamail/*"
  to = "https://api.guerrillamail.com/ajax.php:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Enable SPA prerendering
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; script-src-elem 'self' 'unsafe-inline' blob:; style-src 'self' 'unsafe-inline'; img-src 'self' https: data:; font-src 'self' data:; connect-src 'self' https:; worker-src 'self' blob:; manifest-src 'self';"
    Cache-Control = "public, max-age=31536000"

# Special headers for sitemap.xml and robots.txt
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=3600"